### ISSUE TITLE
Time-series data & heatmap

### ISSUE THREAD

**Issue by JahnNitschke** [andmccall/Colocalization_by_Cross_Correlation#4]
Dear Andrew McCall,

I really like the idea of having a time dependent visualisation of the colocalization, but haven't managed to get to the heatmaps using your plug-in.

I use Fiji on Windows 10 and got your plug-in from the update site. As a toy example I played with stacks of 10 identical black-and-white images (instead of my real microscopy data). The plug-in outputs correctly all the result windows, but gives the same output whether I analyze two stacks or two images (with or without a mask).

Am I just missing a very simple thing? Shouldn't time-series data be submitted as a stack?

Cheers,
jahn

**Comment by andmccall** [comment]
Hi Jahn,

Time-series data can be submitted as a XY stack or a XYZ stack. The important part is that your image dimensions are formatted correctly under Image > Properties. I'm guessing that you are making a stack of 3-spatial dimensions (XYZ), not 2 spatial and one time.  


Andrew
